on:
  push:
    tags:
      - 'v*'

name: Build RRF Configs for Release
jobs:
  build-configs:
    name: Build configuration assets
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build all machine configurations
        run: |
          dist/release-all.sh

  create_release:
    name: Create Release
    needs:
      - build-configs
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          body_path: dist/RELEASE_NOTES.md
          fail_on_unmatched_files: true
          files: |
            dist/*.zip
